### ISSUE TITLE
New stories are not being added

### ISSUE THREAD

**Issue by Nisarga-Developer** [deep5050/Abosar#92]
Hey @deep5050 Greetings! At first, I want to tell you that this is a very awesome project. It is really innovative... But I found out that new stories aren't being added. 

According to the commit history the last story was added on June 13 2021....

Can you please fix this bug??

**Comment by deep5050** [comment]
@Nisarga-Developer thank you for your interest , actually anandabazar website has been changed a lot and the scarper I wrote is somewhat outdated now. I have no time on my hand right now to work on this. someday i'll work on it . also looking for contributord to this project.

**Comment by Nisarga-Developer** [comment]
> @Nisarga-Developer thank you for your interest , actually anandabazar website has been changed a lot and the scarper I wrote is somewhat outdated now. I have no time on my hand right now to work on this. someday i'll work on it . also looking for contributord to this project.

Alright. Anyways the code you wrote was super cool.

Thanks for the reply.

**Comment by Nisarga-Developer** [comment]
Cool, glad to see that you are working on it :)
